title: 3D-Medical-Segmentation-Viewer
logo: /assets/img/CN_Vrt_RGB_HiRes_Lg.png
description: A step-by-step guide to deploying a browser-based 3D medical segmentation application
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
